# burn noticed
text = text.replace("f**king", "fucking")
stopwords = STOPWORDS
stopwords.add("burn")
stopwords.add("noticed")
stopwords.add("comedy")
stopwords.add("central")
stopwords.add("representative")
stopwords.add("representatives")
stopwords.add("takes")
stopwords.add("video")
stopwords.add("new")
stopwords.add("york")
stopwords.add("watch")
stopwords.add("s")
stopwords.add("u")
stopwords.add("congress")
stopwords.add("stewart")
stopwords.add("jon")
stopwords.add("john")
stopwords.add("via")
stopwords.add("committee")
stopwords.add("climate")
stopwords.add("science")
stopwords.add("space")
stopwords.add("technology")
stopwords.add("house")
stopwords.add("show")
stopwords.add("daily")
stopwords.add("change")
stopwords.add("march")
stopwords.add("people")
stopwords.add("global")
stopwords.add("warming")
stopwords.add("take")
stopwords.add("climatechange")
stopwords.add("people's")
stopwords.add("dailyshow")
stopwords.add("jonstewart")
stopwords.add("scientific")
stopwords.add("f")
stopwords.add("us")
stopwords.add("scientist")
stopwords.add("scientists")
stopwords.add("rt")

# steve koonin